### ISSUE TITLE
Alternate URL support

### ISSUE THREAD

**Issue by DonaldTsang** [pastpages/archiveis#16]
For those who blocks certain URLs
- [ ] archive.today
- [ ] archive.li
- [ ] archive.vn
- [ ] archive.ph
- [ ] archive.md

**Comment by Smile4ever** [comment]
If this is optional, yes, that would be welcome.

**Comment by DonaldTsang** [comment]
Yeah it is mainly an issue of fighting against Domain Name Blocking.
