### ISSUE TITLE
via.hypothes.is support

### ISSUE THREAD

**Issue by DonaldTsang** [pastpages/archiveis#17]
Support the nesting of Hypothesis links as an archive link.
e.g. `http://archive.today/?run=1&url=https://via.hypothes.is/https://www.agileservicemanifesto.org/`
where `http://archive.today/?run=1&url=https://via.hypothes.is/` is the prefix and `https://www.agileservicemanifesto.org/` is the URL (encodeURIComponent in JS function)

**Comment by Smile4ever** [comment]
It doesn't seem possible since archive.is takes only the last part: ```https://www.agileservicemanifesto.org/```

**Comment by DonaldTsang** [comment]
That might be just a specific case with one website, does it work with other websites?
Maybe `archive.today/?run=1&url=https://via.hypothes.is/http://darkagilemanifesto.org/` or `archive.today/?run=1&url=https://via.hypothes.is/https://12factor.net/` ?
