### ISSUE TITLE
Wayback Machine support

### ISSUE THREAD

**Issue by DonaldTsang** [pastpages/archiveis#18]
Since https://github.com/motherboardgithub/mass_archive is written in Python and has Wayback Machine support, is it possible to integrate this into archiveis?

https://github.com/oduwsdl/archivenow#example-4 also have a big list in Python
- [ ] WayBack Machine
- [ ]  https://megalodon.jp/
- [ ] https://archive.st/
- (Perma and WebCitation will not accept any more new pages)

**Comment by Smile4ever** [comment]
This would be nice, but doesn't seem to be in the scope of this project.

**Comment by DonaldTsang** [comment]
The reason it might be a good idea to include multiple service is preventative

**Comment by palewire** [comment]
This project is going to stay limited to archive.is. There are separate libraries like savepagenow for the Wayback Machine.
